theme: jekyll-theme-cayman
title: Welcome to my 100 Days of Machine Learning Code
# Your email if you want it to be linked on the contact page
author_email: March Brag
email: cesarbrma91@gmail.com
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
twitter_username: MarchBragagnini
github_username:  marbramen
